const TelegramBot = require("node-telegram-bot-api");
const config = require("config");

/**
 * TelegramConnector sends messages to Telegram groups using Telegram bot API.
 * Bots are used to send error logs and alerts triggered by CollectionActions
 */

/**
 * Use Telegram bot to send an alert triggered by CollectionAction
 * @param {Object} connector Telegram bot configuration
 * @param {Object} message The alert message generated by CollectionAction
 * @returns {Promise<void>}
 */
async function telegramEventReport(connector, message) {
  let bot = new TelegramBot(connector["botToken"]);
  await bot.sendMessage(connector["chatId"], message);
}

async function telegramLogError(req, err) {
  let message = `[ERROR]: ${req.url}\n${err.message}`;
  let bot = new TelegramBot(config.get("telegram_token"));
  await bot.sendMessage(config.get("telegram_chat_id"), message);
}

module.exports = {
  telegramEventReport,
  telegramLogError,
};
